<a href="https://colab.research.google.com/github/Rohith-Rongali/EE5179-2023/blob/main/Tutorials/Tutorial-1/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.24.4


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [2]:
# YOUR CODE STARTS HERE

# YOUR CODE ENDS HERE
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [3]:
# YOUR CODE STARTS HERE
rand_arr = np.random.rand(2,3)  # only from 0 to 1, # in torch it is torch.rand
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.82471533 0.37074813 0.53780882]
 [0.28626353 0.023499   0.47350426]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [4]:
#YOUR CODE STARTS HERE
arr_sum = rand_arr.sum()
arr_mean = rand_arr.mean()
arr_min = rand_arr.min()
arr_max = rand_arr.max()
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 2.5165390648099235
mean: 0.4194231774683206
max: 0.8247153265415946
min:0.023498996496958968


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [8]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
print(f"max value index: {arr.argmax()}\nmin value index: {arr.argmin()}\n")

#Find the indices of maximum and minimum value along each of its columns.
print(f"along each column\nmax value index: {np.argmax(arr, axis = 0)}\nmin value index: {np.argmin(arr, axis = 0)}\n")
#Find the indices of maximum and minimum value along each of the its rows.
print(f"along each row\nmax value index: {np.argmax(arr, axis = 1)}\nmin value index: {np.argmin(arr, axis = 1)}\n")

#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

max value index: 2
min value index: 6

along each column
max value index: [1 1 0 1]
min value index: [0 0 1 0]

along each row
max value index: [2 1]
min value index: [0 2]



Numpy Arrays vs. Python Lists?

    Why the need for numpy arrays? Can't we just use Python lists?
    Iterating over numpy arrays is slow. Slicing is faster

Python lists may contain items of different types. This flexibility comes at a price: Python lists store pointers to memory locations. On the other hand, numpy arrays are typed, where the default type is floating point. Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type. This makes access extremely fast.


If you want to know more, we will suggest that you read this from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for learning numpy, pandas and plotting. All the lessons are available as colab notebooks so that u can try out the commands on your own.

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
c = np.matmul(a, b)
d = np.dot(a, b)
e = a@b
f = a * b #  Hadamard product, element wise product
print(f"{a=},\n{b=}" )
print("mul:\n", c, "\ndot:\n", d,"\nusing @:\n", e, " \n a * b:\n ", f )

a=array([[1, 2],
       [3, 4]]),
b=array([[1, 2],
       [3, 4]])
mul:
 [[ 7 10]
 [15 22]] 
dot:
 [[ 7 10]
 [15 22]] 
using @:
 [[ 7 10]
 [15 22]]  
 a * b:
  [[ 1  4]
 [ 9 16]]


In [13]:
column_sum = a.sum(axis = 0)
print(a,'\n',f"{column_sum=}")

[[1 2]
 [3 4]] 
 column_sum=array([4, 6])


In [11]:
row_sum = a.sum(axis = 1)
print(a,'\n',f"{row_sum=}")

[[1 2]
 [3 4]] 
 row_sum=array([3, 7])
